# topic_proxy/AddPublisher adds a local subscriber on the client side that can be used
# to publish messages at the server side.
#

string topic
string remote_topic               # leave empty if equal to topic
bool compressed
bool latch
---
